// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// birp_interface
void birp_interface(Rcpp::List Parameters, Rcpp::List Data);
RcppExport SEXP _birp_birp_interface(SEXP ParametersSEXP, SEXP DataSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type Parameters(ParametersSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type Data(DataSEXP);
    birp_interface(Parameters, Data);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_birp_birp_interface", (DL_FUNC) &_birp_birp_interface, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_birp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
