#!/bin/sh
rm -f src/Makevars

rm -rf src/birp_cpp/coretools/armadillo/examples/
rm -rf src/birp_cpp/coretools/fmt/test/
rm -rf src/birp_cpp/coretools/fast_float/.github
rm -rf src/birp_cpp/coretools/fmt/.github
rm -rf src/birp_cpp/coretools/json/.github
rm -rf src/birp_cpp/coretools/json/.reuse

rm -f src/birp_cpp/coretools/fast_float/.bazelrc
rm -f src/birp_cpp/coretools/fast_float/.cirrus.yml
rm -f src/birp_cpp/coretools/fast_float/.clang-format
rm -f src/birp_cpp/coretools/fast_float/.travis.yml
rm -f src/birp_cpp/coretools/fmt/.clang-format
rm -f src/birp_cpp/coretools/fmt/support/bazel/.bazelversion
rm -f src/birp_cpp/coretools/json/.cirrus.yml
rm -f src/birp_cpp/coretools/json/.clang-format
rm -f src/birp_cpp/coretools/json/.clang-tidy
rm -f src/birp_cpp/coretools/json/.lgtm.yml
rm -f src/birp_cpp/coretools/json/CITATION.cff

rm -f src/birp_cpp/build/Makefile
rm -f src/birp_cpp/build/_deps/armadillo-build/Makefile
rm -f src/birp_cpp/build/_deps/coretools-build/Makefile
rm -f src/birp_cpp/build/_deps/fmt-build/Makefile
rm -f src/birp_cpp/build/_deps/genometools-build/Makefile
rm -f src/birp_cpp/build/_deps/json-build/Makefile
rm -f src/birp_cpp/build/_deps/stattools-build/Makefile
rm -f src/birp_cpp/coretools/armadillo/tests2/Makefile
rm -f src/birp_cpp/coretools/json/Makefile
